### PR TITLE
Update manifest with correct and valid values

### PR DESCRIPTION
**Pull request by TomSeldon**
- [x] Sets correct permissions
- [x] Add in author names
- [x] Set valid support URL so `gulp validate-xml` can pass
- [x] Add description

### CODE REVIEW

**Comment by chaosmail** [comment]
ok, I guess this means we need to update the addin in the apps dashboard. but this should not be any problem

**Comment by TomSeldon** [comment]
Ok- happy to leave this open for now if it will cause issues

**Comment by chaosmail** [comment]
alright; I am deep deep deep in mammoth to get the ooxml conversion working

**Comment by TomSeldon** [comment]
Anything I can help with? Right now I'm just adding improvements to the view

**Comment by chaosmail** [comment]
that's great! well, turns out that `ooxml` is like unzipped and merged `docx` format - so it is not really working out of the box. I am trying to put all components together that mammoth can also interpret ooxml files

**Comment by chaosmail** [comment]
but it's not working yet, it's very tricky

**Comment by chaosmail** [comment]
probably a reason why they don't support HTML export on word online, because there is no ooxml.js yet

**Comment by TomSeldon** [comment]
If it looks like a dead-end I guess we could look at only supporting Word offline for now? Just makes it tricky to test...

**Comment by chaosmail** [comment]
for word offline i cannot really contribute. but we could check if the coercion type `html` is available, and then use it for conversion.

**Comment by TomSeldon** [comment]
I'm gonna have to call it a night. I haven't done much more to the app other than making the views a little nicer, but I have added some tests and CI integration. Can look at this in the morning and try and get the conversion sorted

**Comment by chaosmail** [comment]
man, you have been on fire - thanks for the great work. I am still trying to add ooxml support :(

**Comment by TomSeldon** [comment]
Easy to get lots done when I'm the one doing the easy stuff! That OOXML stuff looks like a PITA...

**Pull request merged**
